local _, namespace = ...

local L = setmetatable({}, { __index = function(t, k)
	local v = tostring(k)
	rawset(t, k, v)
	return v
end })

namespace.L = L

local LOCALE = GetLocale()

if LOCALE == "enUS" or LOCALE == "enGB" then
	-- No translation needed for english client, so we simply return
	return 
end

if LOCALE == "deDE" then
	-- German translations go here
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "Klingenwirbel"
		L["Adrenaline Rush"] = "Adrenalinrausch"
		L["Preparation"] = "Vorbereitung"
		L["Ghostly Strike"] = "Geisterhafter Stoß"
		L["Premeditation"] = "Konzentration"
		L["Cold Blood"] = "Kaltblütigkeit"

		L["Bestial Wrath"] = "Zorn des Wildtiers"
		L["Intimidation"] = "Einschüchterung"
		L["Deterrence"] = "Abschreckung"
		L["Scatter Shot"] = "Streuschuss"
		L["Aimed Shot"] = "Gezielter Schuss"

		L["Last Stand"] = "Letztes Gefecht"
		L["Sweeping Strikes"] = "Weitreichende Stöße"
		L["Death Wish"] = "Todeswunsch"
		L["Concussion Blow"] = "Erschütternder Schlag"

		L["Inner Focus"] = "Innerer Fokus"
		L["Power Infusion"] = "Seele der Macht"
		L["Silence"] = "Stille"

		L["Elemental Mastery"] = "Elementarbeherrschung"
		L["Stormstrike"] = "Sturmschlag"
		L["Nature's Swiftness"] = "Schnelligkeit der Natur"

		L["Fel Domination"] = "Teufelsbeherrschung"
		L["Amplify Curse"] = "Fluch verstärken"

		L["Divine Favor"] = "Göttliche Gunst"
		L["Holy Shock"] = "Heiliger Schock"
		L["Holy Shield"] = "Heiliger Schild"
		L["Repentance"] = "Buße"

		L["Innervate"] = "Anregen"
		L["Faerie Fire (Feral)"] = "Feenfeuer (Tiergestalt)"
		L["Feral Charge"] = "Wilde Attacke"
		L["Swiftmend"] = "Rasche Heilung"

		L["Presence of Mind"] = "Geistesgegenwart"
		L["Arcane Power"] = "Arkane Macht"
		L["Combustion"] = "Verbrennung"
		L["Cold Snap"] = "Kälteeinbruch"
		L["Ice Block"] = "Eisblock"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "Wille der Verlassenen"
		L["Perception"] = "Wachsamkeit"
		L["War Stomp"] = "Kriegsdonner"
		L["Stoneform"] = "Steingestalt"
		L["Cannibalize"] = "Kannibalismus"
		L["Blood Fury"] = "Kochendes Blut"
		L["Berserking"] = "Berserker"
		L["Shadowmeld"] = "Schattenhaftigkeit"
		L["Escape Artist"] = "Entfesselungskünstler"

		L["Brittle Armor"] = "Spröde Rüstung"
		L["Unstable Power"] = "Instabile Macht"
		L["Restless Strength"] = "Ruhelose Stärke"
		L["Ephemeral Power"] = "Ephemere Macht"
		L["Massive Destruction"] = "Massive Zerstörung"
		L["Arcane Potency"] = "Arkane Kraft"
		L["Energized Shield"] = "Energiegeladener Schild"
		L["Brilliant Light"] = "Gleißendes Licht"
		L["Mar'li's Brain Boost"] = "Mar'lis fokussierte Gedanken"
		L["Burst of Energy"] = "Energieexplosion"
		L["Refocus"] = "Refokussieren"
		L["Venomous Totem"] = "Gifttotem"
		L["Mind Quickening"] = "Gedankensprung"
		L["Gift of Life"] = "Geschenk des Lebens"
		L["Blinding Light"] = "Blendendes Licht"
		L["Nature Aligned"] = "Naturverbundenheit"
		L["Earthstrike"] = "Erdstoß"
		L["Badge of the Swarmguard"] = "Abzeichen der Schwarmwache"
		L["Speed"] = "Tempo"
		L["Immune Root/Snare/Stun"] = "Immunität gegen Unbeweglichkeit/Verlangsamung/Betäuben"
		L["Immune Fear/Polymorph/Snare"] = "Immunität gegen Furcht/Verwandlung/Verlangsamung"
		L["Immune Charm/Fear/Stun"] = "Immunität Bezauberung/Furcht/Betäuben"
		L["Immune Charm/Fear/Polymorph"] = "Immunität Bezauberung/Furcht/Verwandlung"
		L["Immune Fear/Polymorph/Stun"] = "Immunität Furcht/Verwandlung/Betäuben"
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 
		
		L["Frost Reflector"] = "Frostreflektor"
		L["Shadow Reflector"] = "Schattenreflektor"
		L["Fire Reflector"] = "Feuerreflektor"
		
		L["Healing Potion"] = "Heiltrank"
		L["Healing Draught"] = "Heilgebräu"
		L["Restore Mana"] = "Mana wiederherstellen"
		L["Free Action"] = "Freie Aktion"
		L["Living Free Action"] = "Lebhafte freie Aktion"
		L["Invulnerability"] = "Unverwundbarkeit"
		L["Restoration"] = "Wiederherstellung"
		L["Restore Energy"] = "Energie wiederherstellen"

		L["Recently Bandaged"] = "Kürzlich bandagiert"
		L["Iron Grenade"] = "Eisengranate"
		L["Thorium Grenade"] = "Thoriumgranate"
		L["Goblin Sapper Charge"] = "Goblinsche Pioniersprengladung"
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = "Fliehen"
		L["Gnomish Rocket Boots"] = "Gnomen-Raketenstiefel"
		L["Goblin Rocket Boots"] = "Goblin-Raketenstiefel"
		L["Running Speed"] = "Lauftempo"
		L["Gnomish Mind Control Cap"] = "Gnomen-Gedankenkontrollkappe"
		L["Reckless Charge"] = "Tollkühnes Stürmen"

		-- Warrior
		L["Charge"] = "Sturmangriff"
		L["Mocking Blow"] = "Spöttischer Schlag"
		L["Mortal Strike"] = "Tödlicher Stoß"
		L["Overpower"] = "Überwältigen"
		L["Retaliation"] = "Gegenschlag"
		L["Thunder Clap"] = "Donnerknall"
		L["Berserker Rage"] = "Berserkerwut"
		L["Bloodthirst"] = "Blutdurst"
		L["Challenging Shout"] = "Herausforderungsruf"
		L["Intercept"] = "Abfangen"
		L["Intimidating Shout"] = "Drohruf"
		L["Pummel"] = "Zuschlagen"
		L["Recklessness"] = "Tollkühnheit"
		L["Whirlwind"] = "Wirbelwind"
		L["Bloodrage"] = "Blutrausch"
		L["Disarm"] = "Entwaffnen"
		L["Revenge"] = "Rache"
		L["Shield Bash"] = "Schildhieb"
		L["Shield Block"] = "Schildblock"
		L["Shield Slam"] = "Schildschlag"
		L["Shield Wall"] = "Schildwall"

		-- Paladin
		L["Consecration"] = "Weihe"
		L["Exorcism"] = "Exorzismus"
		L["Hammer of Wrath"] = "Hammer des Zorns"
		L["Holy Wrath"] = "Heiliger Zorn"
		L["Lay on Hands"] = "Handauflegung"
		L["Turn Undead"] = "Untote vertreiben"
		L["Blessing of Freedom"] = "Segen der Freiheit"
		L["Blessing of Protection"] = "Segen des Schutzes"
		L["Divine Intervention"] = "Göttliches Eingreifen"
		L["Divine Protection"] = "Göttlicher Schutz"
		L["Divine Shield"] = "Gottesschild"
		L["Hammer of Justice"] = "Hammer der Gerechtigkeit"
		L["Judgement"] = "Richturteil"
		L["Forbearance"] = "Vorahnung"

		-- Mage
		L["Blink"] = "Blinzeln"
		L["Portal: Darnassus"] = "Portal: Darnassus"
		L["Portal: Ironforge"] = "Portal: Ironforge"
		L["Portal: Orgrimmar"] = "Portal: Orgrimmar"
		L["Portal: Stormwind"] = "Portal: Stormwind"
		L["Portal: Thunder Bluff"] = "Portal: Thunder Bluff"
		L["Portal: Undercity"] = "Portal: Undercity"
		L["Blast Wave"] = "Druckwelle"
		L["Fire Blast"] = "Feuerschlag"
		L["Fire Ward"] = "Feuerzauberschutz"
		L["Cone of Cold"] = "Kältekegel"
		L["Frost Nova"] = "Frostnova"
		L["Frost Ward"] = "Frostzauberschutz"
		L["Ice Barrier"] = "Eisbarriere"
		L["Counterspell"] = "Gegenzauber"
		L["Evocation"] = "Hervorrufung"

		-- Rogues
		L["Kidney Shot"] = "Nierenhieb"
		L["Evasion"] = "Entrinnen"
		L["Feint"] = "Finte"
		L["Gouge"] = "Solarplexus"
		L["Kick"] = "Tritt"
		L["Sprint"] = "Sprinten"
		L["Blind"] = "Blenden"
		L["Distract"] = "Ablenken"
		L["Stealth"] = "Verstohlenheit"
		L["Vanish"] = "Verschwinden"

		-- Shaman
		L["Reincarnation"] = "Reinkarnation"
		L["Chain Lightning"] = "Kettenblitzschlag"
		L["Earth Shock"] = "Erdschock"
		L["Earthbind Totem"] = "Totem der Erdbindung"
		L["Fire Nova Totem"] = "Totem der Feuernova"
		L["Flame Shock"] = "Flammenschock"
		L["Frost Shock"] = "Frostschock"
		L["Stoneclaw Totem"] = "Totem der Steinklaue"
		L["Astral Recall"] = "Astraler Rückruf"
		L["Grounding Totem"] = "Totem der Erdung"
		L["Mana Tide Totem"] = "Totem der Manaflut"

		-- Hunters
		L["Scare Beast"] = "Wildtier ängstigen"
		L["Tranquilizing Shot"] = "Einlullender Schuss"
		L["Arcane Shot"] = "Arkaner Schuss"
		L["Concussive Shot"] = "Erschütternder Schuss"
		L["Distracting Shot"] = "Ablenkender Schuss"
		L["Flare"] = "Leuchtfeuer"
		L["Multi-Shot"] = "Mehrfachschuss"
		L["Rapid Fire"] = "Schnellfeuer"
		L["Volley"] = "Salve"
		L["Counterattack"] = "Gegenangriff"
		L["Disengage"] = "Rückzug"
		L["Explosive Trap"] = "Sprengfalle"
		L["Feign Death"] = "Totstellen"
		L["Frost Trap"] = "Frostfalle"
		L["Immolation Trap"] = "Feuerbrandfalle"
		L["Mongoose Bite"] = "Mungobiss"
		L["Raptor Strike"] = "Raptorstoß"
		L["Wyvern Sting"] = "Stich des Flügeldrachen"

		-- Warlocks
		L["Soulstone Resurrection"] = "Seelenstein-Auferstehung"
		L["Curse of Doom"] = "Fluch der Verdammnis"
		L["Death Coil"] = "Todesmantel"
		L["Howl of Terror"] = "Schreckensgeheul"
		L["Inferno"] = "Inferno"
		L["Ritual of Doom"] = "Ritual der Verdammnis"
		L["Shadow Ward"] = "Schattenzauberschutz"
		L["Conflagrate"] = "Feuersbrunst"
		L["Shadowburn"] = "Schattenbrand"
		L["Soul Fire"] = "Seelenfeuer"
		L["Devour Magic"] = "Magie verschlingen"
		L["Spell Lock"] = "Zaubersperre"
		L["Lash of Pain"] = "Schmerzenspeitsche"
		L["Soothing Kiss"] = "Besänftigender Kuss"

		-- Priest
		L["Elune's Grace"] = "Elunes Anmut"
		L["Feedback"] = "Rückkopplung"
		L["Power Word: Shield"] = "Machtwort: Schild"
		L["Desperate Prayer"] = "Verzweifeltes Gebet"
		L["Fear Ward"] = "Furchtzauberschutz"
		L["Devouring Plague"] = "Verschlingende Seuche"
		L["Fade"] = "Verblassen"
		L["Mind Blast"] = "Gedankenschlag"
		L["Psychic Scream"] = "Psychischer Schrei"
		
		-- Druid
		L["Barkskin"] = "Baumrinde"
		L["Faerie Fire"] = "Feenfeuer"
		L["Hurricane"] = "Hurrikan"
		L["Nature's Grasp"] = "Griff der Natur"
		L["Bash"] = "Hieb"
		L["Challenging Roar"] = "Herausforderndes Gebrüll"
		L["Cower"] = "Ducken"
		L["Dash"] = "Spurt"
		L["Enrage"] = "Wutanfall"
		L["Frenzied Regeneration"] = "Rasende Regeneration"
		L["Prowl"] = "Schleichen"
		L["Tiger's Fury"] = "Tigerfuror"
		L["Rebirth"] = "Wiedergeburt"
		L["Tranquility"] = "Gelassenheit"
		
return end

if LOCALE == "frFR" then
	-- French translations go here
		--[[
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = ""
		L["Adrenaline Rush"] = ""
		L["Preparation"] = ""
		L["Ghostly Strike"] = ""
		L["Premeditation"] = ""
		L["Cold Blood"] = ""

		L["Bestial Wrath"] = ""
		L["Intimidation"] = ""
		L["Deterrence"] = ""
		L["Scatter Shot"] = ""
		L["Aimed Shot"] = ""

		L["Last Stand"] = ""
		L["Sweeping Strikes"] = ""
		L["Death Wish"] = ""
		L["Concussion Blow"] = ""

		L["Inner Focus"] = ""
		L["Power Infusion"] = ""
		L["Silence"] = ""

		L["Elemental Mastery"] = ""
		L["Stormstrike"] = ""
		L["Nature's Swiftness"] = ""

		L["Fel Domination"] = ""
		L["Amplify Curse"] = ""

		L["Divine Favor"] = ""
		L["Holy Shock"] = ""
		L["Holy Shield"] = ""
		L["Repentance"] = ""

		L["Innervate"] = ""
		L["Faerie Fire (Feral)"] = ""
		L["Feral Charge"] = ""
		L["Swiftmend"] = ""

		L["Presence of Mind"] = ""
		L["Arcane Power"] = ""
		L["Combustion"] = ""
		L["Cold Snap"] = ""
		L["Ice Block"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = ""
		L["Perception"] = ""
		L["War Stomp"] = ""
		L["Stoneform"] = ""
		L["Cannibalize"] = ""
		L["Blood Fury"] = ""
		L["Berserking"] = ""
		L["Shadowmeld"] = ""
		L["Escape Artist"] = ""

		L["Brittle Armor"] = ""
		L["Unstable Power"] = ""
		L["Restless Strength"] = ""
		L["Ephemeral Power"] = ""
		L["Massive Destruction"] = ""
		L["Arcane Potency"] = ""
		L["Energized Shield"] = ""
		L["Brilliant Light"] = ""
		L["Mar'li's Brain Boost"] = ""
		L["Burst of Energy"] = ""
		L["Refocus"] = ""
		L["Venomous Totem"] = ""
		L["Mind Quickening"] = ""
		L["Gift of Life"] = ""
		L["Blinding Light"] = ""
		L["Nature Aligned"] = ""
		L["Earthstrike"] = ""
		L["Badge of the Swarmguard"] = ""
		L["Speed"] = ""
		L["Immune Root/Snare/Stun"] = ""
		L["Immune Fear/Polymorph/Snare"] = ""
		L["Immune Charm/Fear/Stun"] = ""
		L["Immune Charm/Fear/Polymorph"] = ""
		L["Immune Fear/Polymorph/Stun"] = ""
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = ""
		L["Shadow Reflector"] = ""
		L["Fire Reflector"] = ""
		
		L["Healing Potion"] = ""
		L["Healing Draught"] = ""
		L["Restore Mana"] = ""
		L["Free Action"] = ""
		L["Living Free Action"] = ""
		L["Invulnerability"] = ""
		L["Restoration"] = ""
		L["Restore Energy"] = ""

		L["Recently Bandaged"] = ""
		L["Iron Grenade"] = ""
		L["Thorium Grenade"] = ""
		L["Goblin Sapper Charge"] = ""
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = ""
		L["Gnomish Rocket Boots"] = ""
		L["Goblin Rocket Boots"] = ""
		L["Running Speed"] = ""
		L["Gnomish Mind Control Cap"] = ""
		L["Reckless Charge"] = ""

		-- Warrior
		L["Charge"] = ""
		L["Mocking Blow"] = ""
		L["Mortal Strike"] = ""
		L["Overpower"] = ""
		L["Retaliation"] = ""
		L["Thunder Clap"] = ""
		L["Berserker Rage"] = ""
		L["Bloodthirst"] = ""
		L["Challenging Shout"] = ""
		L["Intercept"] = ""
		L["Intimidating Shout"] = ""
		L["Pummel"] = ""
		L["Recklessness"] = ""
		L["Whirlwind"] = ""
		L["Bloodrage"] = ""
		L["Disarm"] = ""
		L["Revenge"] = ""
		L["Shield Bash"] = ""
		L["Shield Block"] = ""
		L["Shield Slam"] = ""
		L["Shield Wall"] = ""

		-- Paladin
		L["Consecration"] = ""
		L["Exorcism"] = ""
		L["Hammer of Wrath"] = ""
		L["Holy Wrath"] = ""
		L["Lay on Hands"] = ""
		L["Turn Undead"] = ""
		L["Blessing of Freedom"] = ""
		L["Blessing of Protection"] = ""
		L["Divine Intervention"] = ""
		L["Divine Protection"] = ""
		L["Divine Shield"] = ""
		L["Hammer of Justice"] = ""
		L["Judgement"] = ""
		L["Forbearance"] = ""

		-- Mage
		L["Blink"] = ""
		L["Portal: Darnassus"] = ""
		L["Portal: Ironforge"] = ""
		L["Portal: Orgrimmar"] = ""
		L["Portal: Stormwind"] = ""
		L["Portal: Thunder Bluff"] = ""
		L["Portal: Undercity"] = ""
		L["Blast Wave"] = ""
		L["Fire Blast"] = ""
		L["Fire Ward"] = ""
		L["Cone of Cold"] = ""
		L["Frost Nova"] = ""
		L["Frost Ward"] = ""
		L["Ice Barrier"] = ""
		L["Counterspell"] = ""
		L["Evocation"] = ""

		-- Rogues
		L["Kidney Shot"] = ""
		L["Evasion"] = ""
		L["Feint"] = ""
		L["Gouge"] = ""
		L["Kick"] = ""
		L["Sprint"] = ""
		L["Blind"] = ""
		L["Distract"] = ""
		L["Stealth"] = ""
		L["Vanish"] = ""

		-- Shaman
		L["Reincarnation"] = ""
		L["Chain Lightning"] = ""
		L["Earth Shock"] = ""
		L["Earthbind Totem"] = ""
		L["Fire Nova Totem"] = ""
		L["Flame Shock"] = ""
		L["Frost Shock"] = ""
		L["Stoneclaw Totem"] = ""
		L["Astral Recall"] = ""
		L["Grounding Totem"] = ""
		L["Mana Tide Totem"] = ""

		-- Hunters
		L["Scare Beast"] = ""
		L["Tranquilizing Shot"] = ""
		L["Arcane Shot"] = ""
		L["Concussive Shot"] = ""
		L["Distracting Shot"] = ""
		L["Flare"] = ""
		L["Multi-Shot"] = ""
		L["Rapid Fire"] = ""
		L["Volley"] = ""
		L["Counterattack"] = ""
		L["Disengage"] = ""
		L["Explosive Trap"] = ""
		L["Feign Death"] = ""
		L["Frost Trap"] = ""
		L["Immolation Trap"] = ""
		L["Mongoose Bite"] = ""
		L["Raptor Strike"] = ""
		L["Wyvern Sting"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = ""
		L["Curse of Doom"] = ""
		L["Death Coil"] = ""
		L["Howl of Terror"] = ""
		L["Inferno"] = ""
		L["Ritual of Doom"] = ""
		L["Shadow Ward"] = ""
		L["Conflagrate"] = ""
		L["Shadowburn"] = ""
		L["Soul Fire"] = ""
		L["Devour Magic"] = ""
		L["Spell Lock"] = ""
		L["Lash of Pain"] = ""
		L["Soothing Kiss"] = ""

		-- Priest
		L["Elune's Grace"] = ""
		L["Feedback"] = ""
		L["Power Word: Shield"] = ""
		L["Desperate Prayer"] = ""
		L["Fear Ward"] = ""
		L["Devouring Plague"] = ""
		L["Fade"] = ""
		L["Mind Blast"] = ""
		L["Psychic Scream"] = ""
		
		-- Druid
		L["Barkskin"] = ""
		L["Faerie Fire"] = ""
		L["Hurricane"] = ""
		L["Nature's Grasp"] = ""
		L["Bash"] = ""
		L["Challenging Roar"] = ""
		L["Cower"] = ""
		L["Dash"] = ""
		L["Enrage"] = ""
		L["Frenzied Regeneration"] = ""
		L["Prowl"] = ""
		L["Tiger's Fury"] = ""
		L["Rebirth"] = ""
		L["Tranquility"] = ""
		]]--
		
return end

if LOCALE == "esES" or LOCALE == "esMX" then
	-- Spanish translations go here
		--[[
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = ""
		L["Adrenaline Rush"] = ""
		L["Preparation"] = ""
		L["Ghostly Strike"] = ""
		L["Premeditation"] = ""
		L["Cold Blood"] = ""

		L["Bestial Wrath"] = ""
		L["Intimidation"] = ""
		L["Deterrence"] = ""
		L["Scatter Shot"] = ""
		L["Aimed Shot"] = ""

		L["Last Stand"] = ""
		L["Sweeping Strikes"] = ""
		L["Death Wish"] = ""
		L["Concussion Blow"] = ""

		L["Inner Focus"] = ""
		L["Power Infusion"] = ""
		L["Silence"] = ""

		L["Elemental Mastery"] = ""
		L["Stormstrike"] = ""
		L["Nature's Swiftness"] = ""

		L["Fel Domination"] = ""
		L["Amplify Curse"] = ""

		L["Divine Favor"] = ""
		L["Holy Shock"] = ""
		L["Holy Shield"] = ""
		L["Repentance"] = ""

		L["Innervate"] = ""
		L["Faerie Fire (Feral)"] = ""
		L["Feral Charge"] = ""
		L["Swiftmend"] = ""

		L["Presence of Mind"] = ""
		L["Arcane Power"] = ""
		L["Combustion"] = ""
		L["Cold Snap"] = ""
		L["Ice Block"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = ""
		L["Perception"] = ""
		L["War Stomp"] = ""
		L["Stoneform"] = ""
		L["Cannibalize"] = ""
		L["Blood Fury"] = ""
		L["Berserking"] = ""
		L["Shadowmeld"] = ""
		L["Escape Artist"] = ""

		L["Brittle Armor"] = ""
		L["Unstable Power"] = ""
		L["Restless Strength"] = ""
		L["Ephemeral Power"] = ""
		L["Massive Destruction"] = ""
		L["Arcane Potency"] = ""
		L["Energized Shield"] = ""
		L["Brilliant Light"] = ""
		L["Mar'li's Brain Boost"] = ""
		L["Burst of Energy"] = ""
		L["Refocus"] = ""
		L["Venomous Totem"] = ""
		L["Mind Quickening"] = ""
		L["Gift of Life"] = ""
		L["Blinding Light"] = ""
		L["Nature Aligned"] = ""
		L["Earthstrike"] = ""
		L["Badge of the Swarmguard"] = ""
		L["Speed"] = ""
		L["Immune Root/Snare/Stun"] = ""
		L["Immune Fear/Polymorph/Snare"] = ""
		L["Immune Charm/Fear/Stun"] = ""
		L["Immune Charm/Fear/Polymorph"] = ""
		L["Immune Fear/Polymorph/Stun"] = ""
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = ""
		L["Shadow Reflector"] = ""
		L["Fire Reflector"] = ""
		
		L["Healing Potion"] = ""
		L["Healing Draught"] = ""
		L["Restore Mana"] = ""
		L["Free Action"] = ""
		L["Living Free Action"] = ""
		L["Invulnerability"] = ""
		L["Restoration"] = ""
		L["Restore Energy"] = ""

		L["Recently Bandaged"] = ""
		L["Iron Grenade"] = ""
		L["Thorium Grenade"] = ""
		L["Goblin Sapper Charge"] = ""
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = ""
		L["Gnomish Rocket Boots"] = ""
		L["Goblin Rocket Boots"] = ""
		L["Running Speed"] = ""
		L["Gnomish Mind Control Cap"] = ""
		L["Reckless Charge"] = ""

		-- Warrior
		L["Charge"] = ""
		L["Mocking Blow"] = ""
		L["Mortal Strike"] = ""
		L["Overpower"] = ""
		L["Retaliation"] = ""
		L["Thunder Clap"] = ""
		L["Berserker Rage"] = ""
		L["Bloodthirst"] = ""
		L["Challenging Shout"] = ""
		L["Intercept"] = ""
		L["Intimidating Shout"] = ""
		L["Pummel"] = ""
		L["Recklessness"] = ""
		L["Whirlwind"] = ""
		L["Bloodrage"] = ""
		L["Disarm"] = ""
		L["Revenge"] = ""
		L["Shield Bash"] = ""
		L["Shield Block"] = ""
		L["Shield Slam"] = ""
		L["Shield Wall"] = ""

		-- Paladin
		L["Consecration"] = ""
		L["Exorcism"] = ""
		L["Hammer of Wrath"] = ""
		L["Holy Wrath"] = ""
		L["Lay on Hands"] = ""
		L["Turn Undead"] = ""
		L["Blessing of Freedom"] = ""
		L["Blessing of Protection"] = ""
		L["Divine Intervention"] = ""
		L["Divine Protection"] = ""
		L["Divine Shield"] = ""
		L["Hammer of Justice"] = ""
		L["Judgement"] = ""
		L["Forbearance"] = ""

		-- Mage
		L["Blink"] = ""
		L["Portal: Darnassus"] = ""
		L["Portal: Ironforge"] = ""
		L["Portal: Orgrimmar"] = ""
		L["Portal: Stormwind"] = ""
		L["Portal: Thunder Bluff"] = ""
		L["Portal: Undercity"] = ""
		L["Blast Wave"] = ""
		L["Fire Blast"] = ""
		L["Fire Ward"] = ""
		L["Cone of Cold"] = ""
		L["Frost Nova"] = ""
		L["Frost Ward"] = ""
		L["Ice Barrier"] = ""
		L["Counterspell"] = ""
		L["Evocation"] = ""

		-- Rogues
		L["Kidney Shot"] = ""
		L["Evasion"] = ""
		L["Feint"] = ""
		L["Gouge"] = ""
		L["Kick"] = ""
		L["Sprint"] = ""
		L["Blind"] = ""
		L["Distract"] = ""
		L["Stealth"] = ""
		L["Vanish"] = ""

		-- Shaman
		L["Reincarnation"] = ""
		L["Chain Lightning"] = ""
		L["Earth Shock"] = ""
		L["Earthbind Totem"] = ""
		L["Fire Nova Totem"] = ""
		L["Flame Shock"] = ""
		L["Frost Shock"] = ""
		L["Stoneclaw Totem"] = ""
		L["Astral Recall"] = ""
		L["Grounding Totem"] = ""
		L["Mana Tide Totem"] = ""

		-- Hunters
		L["Scare Beast"] = ""
		L["Tranquilizing Shot"] = ""
		L["Arcane Shot"] = ""
		L["Concussive Shot"] = ""
		L["Distracting Shot"] = ""
		L["Flare"] = ""
		L["Multi-Shot"] = ""
		L["Rapid Fire"] = ""
		L["Volley"] = ""
		L["Counterattack"] = ""
		L["Disengage"] = ""
		L["Explosive Trap"] = ""
		L["Feign Death"] = ""
		L["Frost Trap"] = ""
		L["Immolation Trap"] = ""
		L["Mongoose Bite"] = ""
		L["Raptor Strike"] = ""
		L["Wyvern Sting"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = ""
		L["Curse of Doom"] = ""
		L["Death Coil"] = ""
		L["Howl of Terror"] = ""
		L["Inferno"] = ""
		L["Ritual of Doom"] = ""
		L["Shadow Ward"] = ""
		L["Conflagrate"] = ""
		L["Shadowburn"] = ""
		L["Soul Fire"] = ""
		L["Devour Magic"] = ""
		L["Spell Lock"] = ""
		L["Lash of Pain"] = ""
		L["Soothing Kiss"] = ""

		-- Priest
		L["Elune's Grace"] = ""
		L["Feedback"] = ""
		L["Power Word: Shield"] = ""
		L["Desperate Prayer"] = ""
		L["Fear Ward"] = ""
		L["Devouring Plague"] = ""
		L["Fade"] = ""
		L["Mind Blast"] = ""
		L["Psychic Scream"] = ""
		
		-- Druid
		L["Barkskin"] = ""
		L["Faerie Fire"] = ""
		L["Hurricane"] = ""
		L["Nature's Grasp"] = ""
		L["Bash"] = ""
		L["Challenging Roar"] = ""
		L["Cower"] = ""
		L["Dash"] = ""
		L["Enrage"] = ""
		L["Frenzied Regeneration"] = ""
		L["Prowl"] = ""
		L["Tiger's Fury"] = ""
		L["Rebirth"] = ""
		L["Tranquility"] = ""
		]]--
		
return end

if LOCALE == "ptBR" then
	-- Brazilian Portuguese translations go here
	-- Note that the EU Portuguese WoW client also
	-- uses the Brazilian Portuguese locale code.
		--[[
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = ""
		L["Adrenaline Rush"] = ""
		L["Preparation"] = ""
		L["Ghostly Strike"] = ""
		L["Premeditation"] = ""
		L["Cold Blood"] = ""

		L["Bestial Wrath"] = ""
		L["Intimidation"] = ""
		L["Deterrence"] = ""
		L["Scatter Shot"] = ""
		L["Aimed Shot"] = ""

		L["Last Stand"] = ""
		L["Sweeping Strikes"] = ""
		L["Death Wish"] = ""
		L["Concussion Blow"] = ""

		L["Inner Focus"] = ""
		L["Power Infusion"] = ""
		L["Silence"] = ""

		L["Elemental Mastery"] = ""
		L["Stormstrike"] = ""
		L["Nature's Swiftness"] = ""

		L["Fel Domination"] = ""
		L["Amplify Curse"] = ""

		L["Divine Favor"] = ""
		L["Holy Shock"] = ""
		L["Holy Shield"] = ""
		L["Repentance"] = ""

		L["Innervate"] = ""
		L["Faerie Fire (Feral)"] = ""
		L["Feral Charge"] = ""
		L["Swiftmend"] = ""

		L["Presence of Mind"] = ""
		L["Arcane Power"] = ""
		L["Combustion"] = ""
		L["Cold Snap"] = ""
		L["Ice Block"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = ""
		L["Perception"] = ""
		L["War Stomp"] = ""
		L["Stoneform"] = ""
		L["Cannibalize"] = ""
		L["Blood Fury"] = ""
		L["Berserking"] = ""
		L["Shadowmeld"] = ""
		L["Escape Artist"] = ""

		L["Brittle Armor"] = ""
		L["Unstable Power"] = ""
		L["Restless Strength"] = ""
		L["Ephemeral Power"] = ""
		L["Massive Destruction"] = ""
		L["Arcane Potency"] = ""
		L["Energized Shield"] = ""
		L["Brilliant Light"] = ""
		L["Mar'li's Brain Boost"] = ""
		L["Burst of Energy"] = ""
		L["Refocus"] = ""
		L["Venomous Totem"] = ""
		L["Mind Quickening"] = ""
		L["Gift of Life"] = ""
		L["Blinding Light"] = ""
		L["Nature Aligned"] = ""
		L["Earthstrike"] = ""
		L["Badge of the Swarmguard"] = ""
		L["Speed"] = ""
		L["Immune Root/Snare/Stun"] = ""
		L["Immune Fear/Polymorph/Snare"] = ""
		L["Immune Charm/Fear/Stun"] = ""
		L["Immune Charm/Fear/Polymorph"] = ""
		L["Immune Fear/Polymorph/Stun"] = ""
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = ""
		L["Shadow Reflector"] = ""
		L["Fire Reflector"] = ""
		
		L["Healing Potion"] = ""
		L["Healing Draught"] = ""
		L["Restore Mana"] = ""
		L["Free Action"] = ""
		L["Living Free Action"] = ""
		L["Invulnerability"] = ""
		L["Restoration"] = ""
		L["Restore Energy"] = ""

		L["Recently Bandaged"] = ""
		L["Iron Grenade"] = ""
		L["Thorium Grenade"] = ""
		L["Goblin Sapper Charge"] = ""
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = ""
		L["Gnomish Rocket Boots"] = ""
		L["Goblin Rocket Boots"] = ""
		L["Running Speed"] = ""
		L["Gnomish Mind Control Cap"] = ""
		L["Reckless Charge"] = ""

		-- Warrior
		L["Charge"] = ""
		L["Mocking Blow"] = ""
		L["Mortal Strike"] = ""
		L["Overpower"] = ""
		L["Retaliation"] = ""
		L["Thunder Clap"] = ""
		L["Berserker Rage"] = ""
		L["Bloodthirst"] = ""
		L["Challenging Shout"] = ""
		L["Intercept"] = ""
		L["Intimidating Shout"] = ""
		L["Pummel"] = ""
		L["Recklessness"] = ""
		L["Whirlwind"] = ""
		L["Bloodrage"] = ""
		L["Disarm"] = ""
		L["Revenge"] = ""
		L["Shield Bash"] = ""
		L["Shield Block"] = ""
		L["Shield Slam"] = ""
		L["Shield Wall"] = ""

		-- Paladin
		L["Consecration"] = ""
		L["Exorcism"] = ""
		L["Hammer of Wrath"] = ""
		L["Holy Wrath"] = ""
		L["Lay on Hands"] = ""
		L["Turn Undead"] = ""
		L["Blessing of Freedom"] = ""
		L["Blessing of Protection"] = ""
		L["Divine Intervention"] = ""
		L["Divine Protection"] = ""
		L["Divine Shield"] = ""
		L["Hammer of Justice"] = ""
		L["Judgement"] = ""
		L["Forbearance"] = ""

		-- Mage
		L["Blink"] = ""
		L["Portal: Darnassus"] = ""
		L["Portal: Ironforge"] = ""
		L["Portal: Orgrimmar"] = ""
		L["Portal: Stormwind"] = ""
		L["Portal: Thunder Bluff"] = ""
		L["Portal: Undercity"] = ""
		L["Blast Wave"] = ""
		L["Fire Blast"] = ""
		L["Fire Ward"] = ""
		L["Cone of Cold"] = ""
		L["Frost Nova"] = ""
		L["Frost Ward"] = ""
		L["Ice Barrier"] = ""
		L["Counterspell"] = ""
		L["Evocation"] = ""

		-- Rogues
		L["Kidney Shot"] = ""
		L["Evasion"] = ""
		L["Feint"] = ""
		L["Gouge"] = ""
		L["Kick"] = ""
		L["Sprint"] = ""
		L["Blind"] = ""
		L["Distract"] = ""
		L["Stealth"] = ""
		L["Vanish"] = ""

		-- Shaman
		L["Reincarnation"] = ""
		L["Chain Lightning"] = ""
		L["Earth Shock"] = ""
		L["Earthbind Totem"] = ""
		L["Fire Nova Totem"] = ""
		L["Flame Shock"] = ""
		L["Frost Shock"] = ""
		L["Stoneclaw Totem"] = ""
		L["Astral Recall"] = ""
		L["Grounding Totem"] = ""
		L["Mana Tide Totem"] = ""

		-- Hunters
		L["Scare Beast"] = ""
		L["Tranquilizing Shot"] = ""
		L["Arcane Shot"] = ""
		L["Concussive Shot"] = ""
		L["Distracting Shot"] = ""
		L["Flare"] = ""
		L["Multi-Shot"] = ""
		L["Rapid Fire"] = ""
		L["Volley"] = ""
		L["Counterattack"] = ""
		L["Disengage"] = ""
		L["Explosive Trap"] = ""
		L["Feign Death"] = ""
		L["Frost Trap"] = ""
		L["Immolation Trap"] = ""
		L["Mongoose Bite"] = ""
		L["Raptor Strike"] = ""
		L["Wyvern Sting"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = ""
		L["Curse of Doom"] = ""
		L["Death Coil"] = ""
		L["Howl of Terror"] = ""
		L["Inferno"] = ""
		L["Ritual of Doom"] = ""
		L["Shadow Ward"] = ""
		L["Conflagrate"] = ""
		L["Shadowburn"] = ""
		L["Soul Fire"] = ""
		L["Devour Magic"] = ""
		L["Spell Lock"] = ""
		L["Lash of Pain"] = ""
		L["Soothing Kiss"] = ""

		-- Priest
		L["Elune's Grace"] = ""
		L["Feedback"] = ""
		L["Power Word: Shield"] = ""
		L["Desperate Prayer"] = ""
		L["Fear Ward"] = ""
		L["Devouring Plague"] = ""
		L["Fade"] = ""
		L["Mind Blast"] = ""
		L["Psychic Scream"] = ""
		
		-- Druid
		L["Barkskin"] = ""
		L["Faerie Fire"] = ""
		L["Hurricane"] = ""
		L["Nature's Grasp"] = ""
		L["Bash"] = ""
		L["Challenging Roar"] = ""
		L["Cower"] = ""
		L["Dash"] = ""
		L["Enrage"] = ""
		L["Frenzied Regeneration"] = ""
		L["Prowl"] = ""
		L["Tiger's Fury"] = ""
		L["Rebirth"] = ""
		L["Tranquility"] = ""
		]]--
		
return end

if LOCALE == "ruRU" then
	-- Russian translations go here
	-- Thanks to Мрмоу for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "Шквал клинков"
		L["Adrenaline Rush"] = "Выброс адренлина"
		L["Preparation"] = "Подготовка"
		L["Ghostly Strike"] = "Призрачный удар"
		L["Premeditation"] = "Умысел"
		L["Cold Blood"] = "Хладнокровие"

		L["Bestial Wrath"] = "Звериный гнев"
		L["Intimidation"] = "Устрашение"
		L["Deterrence"] = "Сдерживание"
		L["Scatter Shot"] = "Дезориентирующий выстрел"
		L["Aimed Shot"] = "Прицельный выстрел"

		L["Last Stand"] = "Ни шагу назад"
		L["Sweeping Strikes"] = "Размашистые удары"
		L["Death Wish"] = "Инстинкт смерти"
		L["Concussion Blow"] = "Оглушающий удар"

		L["Inner Focus"] = "Внутреннее сосредоточение"
		L["Power Infusion"] = "Придание сил"
		L["Silence"] = "Молчание"

		L["Elemental Mastery"] = "Покорение стихий"
		L["Stormstrike"] = "Удар бури"
		L["Nature's Swiftness"] = "Природная стремительность"

		L["Fel Domination"] = "Господство Скверны"
		L["Amplify Curse"] = "Усиление проклятия"

		L["Divine Favor"] = "Божественное одобрение"
		L["Holy Shock"] = "Шок небес"
		L["Holy Shield"] = "Щит небес"
		L["Repentance"] = "Покаяние"

		L["Innervate"] = "Озарение"
		L["Faerie Fire (Feral)"] = "Волшебный огонь (сила зверя)"
		L["Feral Charge"] = "Звериная атака"
		L["Swiftmend"] = "Быстрое восстановление"

		L["Presence of Mind"] = "Присутствие разума"
		L["Arcane Power"] = "Мощь тайной магии"
		L["Combustion"] = "Возгорание"
		L["Cold Snap"] = "Холодная хватка"
		L["Ice Block"] = "Ледяная глыба"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "Воля Отрекшихся"
		L["Perception"] = "Внимательность"
		L["War Stomp"] = "Громовая поступь"
		L["Stoneform"] = "Каменная форма"
		L["Cannibalize"] = "Каннибализм"
		L["Blood Fury"] = "Кровавое неистовство"
		L["Berserking"] = "Боевое исступление"
		L["Shadowmeld"] = "Слиться с тенью"
		L["Escape Artist"] = "Мастер побега"

		L["Brittle Armor"] = "Хрупкие доспехи"
		L["Unstable Power"] = "Изменчивая сила"
		L["Restless Strength"] = "Неодолимая сила"
		L["Ephemeral Power"] = "Эфимерная власть"
		L["Massive Destruction"] = "Массовое разрушение"
		L["Arcane Potency"] = "Чародейское могущество"
		L["Energized Shield"] = "Энергетический щит"
		L["Brilliant Light"] = "Бриллиантовый свет"
		L["Mar'li's Brain Boost"] = "Стимулятор мозга Марли"
		--L["Burst of Energy"] = "Прилив сил" -- Shares the same name with mage evocation
		L["Refocus"] = "Восстановление способностей"
		L["Venomous Totem"] = "Ядовитый тотем"
		L["Mind Quickening"] = "Скорость мысли"
		L["Gift of Life"] = "Дар жизни"
		L["Blinding Light"] = "Слепящий свет"
		L["Nature Aligned"] = "Упорядочение Природы"
		L["Earthstrike"] = "Земной удар"
		L["Badge of the Swarmguard"] = "Жетон Стража Роя"
		L["Speed"] = "Скорость"
		L["Immune Root/Snare/Stun"] = "Неуязвимость к обездвиживанию/ловушкам/оглушению"
		L["Immune Fear/Polymorph/Snare"] = "Неуязвимость к страху/превращению/сковывания"
		L["Immune Charm/Fear/Stun"] = "Неуязвимость к подчинению/страху/оглушению"
		L["Immune Charm/Fear/Polymorph"] = "Неуязвимость к подчинению/страху/превращению"
		L["Immune Fear/Polymorph/Stun"] = "Неуязвимость к страху/превращению/оглушению"
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = "Зеркало Льда"
		L["Shadow Reflector"] = "Отражатель тьмы"
		L["Fire Reflector"] = "Отражатель пламени"
		
		L["Healing Potion"] = "Лечебное зелье"
		L["Healing Draught"] = "Исцеляющее зелье"
		L["Restore Mana"] = "Восполнение маны"
		L["Free Action"] = "Свобода действий"
		L["Living Free Action"] = "Живая свобода действий"
		L["Invulnerability"] = "Неуязвимость"
		--L["Restoration"] = "Восстановление" -- Share same name with druid regrowth
		L["Restore Energy"] = "Восполнение энергии"

		L["Recently Bandaged"] = "Недавняя перевязка"
		L["Iron Grenade"] = "Железная граната"
		L["Thorium Grenade"] = "Ториевая граната"
		L["Goblin Sapper Charge"] = "Гоблинский саперный заряд"
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = "Бегство"
		L["Gnomish Rocket Boots"] = "Гномьи реактивные сапоги"
		L["Goblin Rocket Boots"] = "Гоблинские реактивные сапоги"
		L["Running Speed"] = "Скорость бега"
		L["Gnomish Mind Control Cap"] = "Гномья шапка контроля над разумом"
		L["Reckless Charge"] = "Безрассудная атака"

		-- Warrior
		L["Charge"] = "Рывок"
		L["Mocking Blow"] = "Дразнящий удар"
		L["Mortal Strike"] = "Смертельный удар"
		L["Overpower"] = "Превосходство"
		L["Retaliation"] = "Возмездие"
		L["Thunder Clap"] = "Удар грома"
		L["Berserker Rage"] = "Ярость берсерка"
		L["Bloodthirst"] = "Кровожадность"
		L["Challenging Shout"] = "Вызывающий крик"
		L["Intercept"] = "Перехват"
		L["Intimidating Shout"] = "Устрашающий крик"
		L["Pummel"] = "Зуботычина"
		L["Recklessness"] = "Безрассудство"
		L["Whirlwind"] = "Вихрь"
		L["Bloodrage"] = "Кровавая ярость"
		L["Disarm"] = "Разоружение"
		L["Revenge"] = "Реванш"
		L["Shield Bash"] = "Удар щитом"
		L["Shield Block"] = "Блок щитом"
		L["Shield Slam"] = "Скорушение щитом"
		L["Shield Wall"] = "Глухая оборона"

		-- Paladin
		L["Consecration"] = "Освящение"
		L["Exorcism"] = "Экзорцизм"
		L["Hammer of Wrath"] = "Молот гнева"
		L["Holy Wrath"] = "Гнев небес"
		L["Lay on Hands"] = "Возложение рук"
		L["Turn Undead"] = "Изгнание нежити"
		L["Blessing of Freedom"] = "Благословение cвободы"
		L["Blessing of Protection"] = "Благословение защиты"
		L["Divine Intervention"] = "Божественное вмешательство"
		L["Divine Protection"] = "Божественная защита"
		L["Divine Shield"] = "Божественный щит"
		L["Hammer of Justice"] = "Молот правосудия"
		L["Judgement"] = "Правосудие"
		L["Forbearance"] = "Воздержанность"

		-- Mage
		L["Blink"] = "Скачок"
		L["Portal: Darnassus"] = "Портал в Дарнасс"
		L["Portal: Ironforge"] = "Портал в Стальгорн"
		L["Portal: Orgrimmar"] = "Портал в Оргриммар"
		L["Portal: Stormwind"] = "Портал в Штормград"
		L["Portal: Thunder Bluff"] = "Портал в Громовой Утес"
		L["Portal: Undercity"] = "Портал в Подгород"
		L["Blast Wave"] = "Взрывная волна"
		L["Fire Blast"] = "Огненный взрыв"
		L["Fire Ward"] = "Защита от огня"
		L["Cone of Cold"] = "Конус холода"
		L["Frost Nova"] = "Кольцо льда"
		L["Frost Ward"] = "Защита от магии льда"
		L["Ice Barrier"] = "Ледяная преграда"
		L["Counterspell"] = "Антимагия"
		L["Evocation"] = "Прилив сил"

		-- Rogues
		L["Kidney Shot"] = "Удар по почкам"
		L["Evasion"] = "Ускользание"
		L["Feint"] = "Ложный выпад"
		L["Gouge"] = "Парализующий удар"
		L["Kick"] = "Пинок"
		L["Sprint"] = "Спринт"
		L["Blind"] = "Ослепление"
		L["Distract"] = "Отвлечение"
		L["Stealth"] = "Незаметность"
		L["Vanish"] = "Исчезновение"

		-- Shaman
		L["Reincarnation"] = "Восстание из мертвых"
		L["Chain Lightning"] = "Цепная молния"
		L["Earth Shock"] = "Земной шок"
		L["Earthbind Totem"] = "Тотем оков земли"
		L["Fire Nova Totem"] = "Тотем кольца огня"
		L["Flame Shock"] = "Огненный шок"
		L["Frost Shock"] = "Ледяной шок"
		L["Stoneclaw Totem"] = "Тотем каменного когтя"
		L["Astral Recall"] = "Астральное возвращение"
		L["Grounding Totem"] = "Тотем заземления"
		L["Mana Tide Totem"] = "Тотем прилива маны"

		-- Hunters
		L["Scare Beast"] = "Отпугивание зверя"
		L["Tranquilizing Shot"] = "Усмиряющий выстрел"
		L["Arcane Shot"] = "Чародейский выстрел"
		L["Concussive Shot"] = "Шокирующий выстрел"
		L["Distracting Shot"] = "Отвлекающий выстрел"
		L["Flare"] = "Осветительная ракета"
		L["Multi-Shot"] = "Залп"
		L["Rapid Fire"] = "Быстрая стрельба"
		L["Volley"] = "Град стрел"
		L["Counterattack"] = "Контратака"
		L["Disengage"] = "Отрыв"
		L["Explosive Trap"] = "Взрывная ловушка"
		L["Feign Death"] = "Притвориться мертвым"
		L["Frost Trap"] = "Ледяная ловушка"
		L["Immolation Trap"] = "Обжигающая ловушка"
		L["Mongoose Bite"] = "Укус мангуста"
		L["Raptor Strike"] = "Удар ящера"
		L["Wyvern Sting"] = "Жало виверны"

		-- Warlocks
		L["Soulstone Resurrection"] = "Воскрешение камнем души"
		L["Curse of Doom"] = "Проклятие рока"
		L["Death Coil"] = "Лик смерти"
		L["Howl of Terror"] = "Вой ужаса"
		L["Inferno"] = "Инфернал"
		L["Ritual of Doom"] = "Ритуал Рока"
		L["Shadow Ward"] = "Защита от темной магии"
		L["Conflagrate"] = "Поджигание"
		L["Shadowburn"] = "Ожог тьмы"
		L["Soul Fire"] = "Ожог души"
		L["Devour Magic"] = "Пожирание магии"
		L["Spell Lock"] = "Запрет чар"
		L["Lash of Pain"] = "Всплеск боли"
		L["Soothing Kiss"] = "Утешительный поцелуй"

		-- Priest
		L["Elune's Grace"] = "Благодать Элуны"
		L["Feedback"] = "Ответная реакция"
		L["Power Word: Shield"] = "Слово силы: Щит"
		L["Desperate Prayer"] = "Молитва отчаяния"
		L["Fear Ward"] = "Защита от страха"
		L["Devouring Plague"] = "Всепожирающая чума"
		L["Fade"] = "Уход в тень"
		L["Mind Blast"] = "Взрыв разума"
		L["Psychic Scream"] = "Ментальный крик"
		
		-- Druid
		L["Barkskin"] = "Дубовая кожа"
		L["Faerie Fire"] = "Волшебный огонь"
		L["Hurricane"] = "Гроза"
		L["Nature's Grasp"] = "Природный захват"
		L["Bash"] = "Оглушить"
		L["Challenging Roar"] = "Вызывающий рев"
		L["Cower"] = "Попятиться"
		L["Dash"] = "Порыв"
		L["Enrage"] = "Исступление"
		L["Frenzied Regeneration"] = "Неистовое восстановление"
		L["Prowl"] = "Крадущийся зверь"
		L["Tiger's Fury"] = "Тигриное неистовство"
		L["Rebirth"] = "Возрождение"
		L["Tranquility"] = "Спокойствие"
		
return end

if LOCALE == "koKR" then
	-- Korean translations go here
	-- Thanks to 좌상탄 for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "폭풍의 칼날"
		L["Adrenaline Rush"] = "아드레날린 촉진"
		L["Preparation"] = "마음가짐"
		L["Ghostly Strike"] = "그림자 일격"
		L["Premeditation"] = "사전계획"
		L["Cold Blood"] = "냉혈"

		L["Bestial Wrath"] = "야수의 격노"
		L["Intimidation"] = "위협"
		L["Deterrence"] = "공격 저지"
		L["Scatter Shot"] = "산탄 사격"
		L["Aimed Shot"] = "조준 사격"

		L["Last Stand"] = "최후의 저항"
		L["Sweeping Strikes"] = "휩쓸기 일격"
		L["Death Wish"] = "죽음의 소원"
		L["Concussion Blow"] = "충격의 일격"

		L["Inner Focus"] = "내면의 집중력"
		L["Power Infusion"] = "마력 주입"
		L["Silence"] = "침묵"

		L["Elemental Mastery"] = "정기의 깨달음"
		L["Stormstrike"] = "폭풍의 일격"
		L["Nature's Swiftness"] = "자연의 신속함"

		L["Fel Domination"] = "마의 지배"
		L["Amplify Curse"] = "저주 증폭"

		L["Divine Favor"] = "신의 은총"
		L["Holy Shock"] = "신성 충격"
		L["Holy Shield"] = "신성한 방패"
		L["Repentance"] = "참회"

		L["Innervate"] = "정신 자극"
		L["Feral Charge"] = "야성의 돌진"
		L["Swiftmend"] = "신속한 치유"

		L["Presence of Mind"] = "냉정"
		L["Arcane Power"] = "신비의 마법 강화"
		L["Combustion"] = "발화"
		L["Cold Snap"] = "매서운 한파"
		L["Ice Block"] = "얼음 방패"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "포세이큰의 의지"
		L["Perception"] = "직관력"
		L["War Stomp"] = "전투 발구르기"
		L["Stoneform"] = "석화"
		L["Cannibalize"] = "시체먹기"
		L["Blood Fury"] = "피의 격노"
		L["Berserking"] = "광폭화"
		L["Shadowmeld"] = "그림자 숨기"
		L["Escape Artist"] = "탈출의 명수"

		L["Brittle Armor"] = "불완전한 갑옷"
		L["Unstable Power"] = "불안정한 마력"
		L["Restless Strength"] = "불안정한 힘"
		L["Ephemeral Power"] = "마력의 힘"
		L["Massive Destruction"] = "잔혹한 파괴"
		L["Arcane Potency"] = "신비한 잠재력"
		L["Energized Shield"] = "보호막 강화"
		L["Brilliant Light"] = "찬란한 빛"
		L["Mar'li's Brain Boost"] = "말리의 사고 촉진"
		L["Burst of Energy"] = "기력 폭발"
		L["Refocus"] = "주의 집중"
		L["Venomous Totem"] = "맹독의 토템"
		L["Mind Quickening"] = "사고 촉진"
		L["Gift of Life"] = "생명의 선물"
		L["Blinding Light"] = "빛의 결속"
		L["Nature Aligned"] = "자연 동화"
		L["Earthstrike"] = "대지의 격동"
		L["Badge of the Swarmguard"] = "전투감시병의 휘장"
		L["Speed"] = "신속"
		L["Immune Root/Snare/Stun"] = "이동 불가/덫/기절 면역"
		L["Immune Fear/Polymorph/Snare"] = "공포/변이/덫 면역"
		L["Immune Charm/Fear/Stun"] = "현혹/공포/기절 면역"
		L["Immune Charm/Fear/Polymorph"] = "현혹/공포/변이 변역"
		L["Immune Fear/Polymorph/Stun"] = "공포/변이/기절 면역"
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = "회전냉각식 냉기 반사기"
		L["Shadow Reflector"] = "초광자 암흑 반사기"
		L["Fire Reflector"] = "극고온 화염 반사기"
		
		L["Healing Potion"] = "치유 물약"
		L["Healing Draught"] = "치유 비약"
		L["Restore Mana"] = "마나 회복"
		L["Free Action"] = "자유 의지"
		L["Living Free Action"] = "자유 행동의 물약"
		L["Invulnerability"] = "무적"
		L["Restoration"] = "복원"
		L["Restore Energy"] = "기력 회복"

		L["Recently Bandaged"] = "붕대 치료"
		L["Iron Grenade"] = "철제 수류탄"
		L["Thorium Grenade"] = "토륨 수류탄"
		L["Goblin Sapper Charge"] = "고블린 공병 폭탄"
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = "도주"
		L["Gnomish Rocket Boots"] = "노움 로켓 장화"
		L["Goblin Rocket Boots"] = "고블린 로켓 장화"
		L["Running Speed"] = "이동 속도 증가"
		L["Gnomish Mind Control Cap"] = "노움 정신 지배 모자"
		L["Reckless Charge"] = "무모한 돌진"

		-- Warrior
		L["Charge"] = "돌진"
		L["Mocking Blow"] = "도발의 일격"
		L["Mortal Strike"] = "죽음의 일격"
		L["Overpower"] = "제압"
		L["Retaliation"] = "보복"
		L["Thunder Clap"] = "천둥벼락"
		L["Berserker Rage"] = "광전사의 격노"
		L["Bloodthirst"] = "피의 갈증"
		L["Challenging Shout"] = "도전의 외침"
		L["Intercept"] = "봉쇄"
		L["Intimidating Shout"] = "위협의 외침"
		L["Pummel"] = "자루 공격"
		L["Recklessness"] = "무모한 희생"
		L["Whirlwind"] = "소용돌이"
		L["Bloodrage"] = "피의 분노"
		L["Disarm"] = "무장 해제"
		L["Revenge"] = "복수"
		L["Shield Bash"] = "방패 밀쳐내기"
		L["Shield Block"] = "방패 막기"
		L["Shield Slam"] = "방패 밀쳐내기"
		L["Shield Wall"] = "방패의 벽"

		-- Paladin
		L["Consecration"] = "신성화"
		L["Exorcism"] = "퇴마술"
		L["Hammer of Wrath"] = "천벌의 망치"
		L["Holy Wrath"] = "신의 격노"
		L["Lay on Hands"] = "신의 축복"
		L["Turn Undead"] = "언데드 퇴치"
		L["Blessing of Freedom"] = "자유의 축복"
		L["Blessing of Protection"] = "보호의 축복"
		L["Divine Intervention"] = "성스러운 중재"
		L["Divine Protection"] = "신의 가호"
		L["Divine Shield"] = "천상의 보호막"
		L["Hammer of Justice"] = "심판의 망치"
		L["Judgement"] = "심판"
		L["Forbearance"] = "참을성"

		-- Mage
		L["Blink"] = "점멸"
		L["Portal: Darnassus"] = "차원의 문: 다르나서스"
		L["Portal: Ironforge"] = "차원의 문: 아이언포지"
		L["Portal: Orgrimmar"] = "차원의 문: 오그리마"
		L["Portal: Stormwind"] = "차원의 문: 스톰윈드"
		L["Portal: Thunder Bluff"] = "차원의 문: 썬더 블러프"
		L["Portal: Undercity"] = "차원의 문: 언더시티"
		L["Blast Wave"] = "화염 폭풍"
		L["Fire Blast"] = "화염 작열"
		L["Fire Ward"] = "화염계 수호"
		L["Cone of Cold"] = "냉기 돌풍"
		L["Frost Nova"] = "얼음 회오리"
		L["Frost Ward"] = "냉기계 수호"
		L["Ice Barrier"] = "얼음 보호막"
		L["Counterspell"] = "마법 차단"
		L["Evocation"] = "환기"

		-- Rogues
		L["Kidney Shot"] = "급소 가격"
		L["Evasion"] = "회피"
		L["Feint"] = "교란"
		L["Gouge"] = "후려치기"
		L["Kick"] = "발차기"
		L["Sprint"] = "전력 질주"
		L["Blind"] = "실명"
		L["Distract"] = "혼란"
		L["Stealth"] = "은신"
		L["Vanish"] = "소멸"

		-- Shaman
		L["Reincarnation"] = "윤회"
		L["Chain Lightning"] = "연쇄 번개"
		L["Earth Shock"] = "대지 충격"
		L["Earthbind Totem"] = "속박의 토템"
		L["Fire Nova Totem"] = "불꽃 회오리 토템"
		L["Flame Shock"] = "화염 충격"
		L["Frost Shock"] = "냉기 충격"
		L["Stoneclaw Totem"] = "돌발톱 토템"
		L["Astral Recall"] = "영혼의 귀환"
		L["Grounding Totem"] = "마법정화 토템"
		L["Mana Tide Totem"] = "마나 해일 토템"

		-- Hunters
		L["Scare Beast"] = "야수 겁주기"
		L["Tranquilizing Shot"] = "평정의 사격"
		L["Arcane Shot"] = "신비한 사격"
		L["Concussive Shot"] = "충격포"
		L["Distracting Shot"] = "견제 사격"
		L["Flare"] = "섬광"
		L["Multi-Shot"] = "일제 사격"
		L["Rapid Fire"] = "속사"
		L["Volley"] = "연발 사격"
		L["Counterattack"] = "역습"
		L["Disengage"] = "철수"
		L["Explosive Trap"] = "폭발의 덫"
		L["Feign Death"] = "죽은척하기"
		L["Freezing Trap"] = "얼음의 덫"
		L["Frost Trap"] = "냉기의 덫"
		L["Immolation Trap"] = "제물의 덫"
		L["Mongoose Bite"] = "살쾡이의 이빨"
		L["Raptor Strike"] = "랩터의 일격"
		L["Wyvern Sting"] = "비룡 쐐기"

		-- Warlocks
		L["Soulstone Resurrection"] = "영혼석 부활"
		L["Curse of Doom"] = "파멸의 저주"
		L["Death Coil"] = "죽음의 고리"
		L["Howl of Terror"] = "공포의 울부짖음"
		L["Inferno"] = "불지옥"
		L["Ritual of Doom"] = "파멸의 의식"
		L["Shadow Ward"] = "암흑계 수호"
		L["Conflagrate"] = "점화"
		L["Shadowburn"] = "어둠의 연소"
		L["Soul Fire"] = "영혼의 불꽃"
		L["Devour Magic"] = "마법 삼키기"
		L["Spell Lock"] = "주문 잠금"
		L["Lash of Pain"] = "고통의 채찍"
		L["Soothing Kiss"] = "유혹의 입맞춤"

		-- Priest
		L["Elune's Grace"] = "엘룬의 은총"
		L["Feedback"] = "역순환"
		L["Power Word: Shield"] = "신의 권능: 보호막"
		L["Desperate Prayer"] = "구원의 기도"
		L["Fear Ward"] = "공포의 수호물"
		L["Devouring Plague"] = "파멸의 역병"
		L["Fade"] = "소실"
		L["Mind Blast"] = "정신 분열"
		L["Psychic Scream"] = "영혼의 절규"
		
		-- Druid
		L["Barkskin"] = "나무 껍질"
		L["Faerie Fire"] = "요정의 불꽃"
		L["Hurricane"] = "허리케인"
		L["Nature's Grasp"] = "자연의 손아귀"
		L["Bash"] = "강타"
		L["Challenging Roar"] = "도전의 포효"
		L["Cower"] = "웅크리기"
		L["Dash"] = "질주"
		L["Enrage"] = "분노"
		L["Frenzied Regeneration"] = "광포한 재생력"
		L["Prowl"] = "숨기"
		L["Tiger's Fury"] = "맹공격"
		L["Rebirth"] = "환생"
		L["Tranquility"] = "평온"
		
return end

if LOCALE == "zhCN" then
	-- Simplified Chinese translations go here
	-- Thanks to ming1455 for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "剑刃乱舞"
		L["Adrenaline Rush"] = "冲动"
		L["Preparation"] = "伺机待发"
		L["Ghostly Strike"] = "鬼魅攻击"
		L["Premeditation"] = "预谋"
		L["Cold Blood"] = "冷血"

		L["Bestial Wrath"] = "血性狂暴"
		L["Intimidation"] = "胁迫"
		L["Deterrence"] = "猛禽一击"
		L["Scatter Shot"] = "震荡射击"
		L["Aimed Shot"] = "瞄准射击"

		L["Last Stand"] = "破釜沉舟"
		L["Sweeping Strikes"] = "横扫攻击"
		L["Death Wish"] = "死亡之愿"
		L["Concussion Blow"] = "震荡猛击"

		L["Inner Focus"] = "心灵专注"
		L["Power Infusion"] = "能量灌注"
		L["Silence"] = "沉默"

		L["Elemental Mastery"] = "元素掌握"
		L["Stormstrike"] = "风暴打击"
		L["Nature's Swiftness"] = "自然迅捷"

		L["Fel Domination"] = "恶魔支配"
		L["Amplify Curse"] = "诅咒增幅"

		L["Divine Favor"] = "神恩术"
		L["Holy Shock"] = "神圣震击"
		L["Holy Shield"] = "神圣之盾"
		L["Repentance"] = "忏悔"

		L["Innervate"] = "激活"
		L["Faerie Fire (Feral)"] = "精灵之火（野性）"
		L["Feral Charge"] = "野性冲锋"
		L["Swiftmend"] = "迅捷治愈"

		L["Presence of Mind"] = "气定神闲"
		L["Arcane Power"] = "奥术强化"
		L["Combustion"] = "燃烧"
		L["Cold Snap"] = "急速冷却"
		L["Ice Block"] = "寒冰屏障"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "被遗忘者的意志"
		L["Perception"] = "感知"
		L["War Stomp"] = "战争践踏"
		L["Stoneform"] = "石像形态"
		L["Cannibalize"] = "食尸"
		L["Blood Fury"] = "血性狂暴"
		L["Berserking"] = "狂暴"
		L["Shadowmeld"] = "影遁"
		L["Escape Artist"] = "逃命专家"

		L["Brittle Armor"] = "脆弱护甲"
		L["Unstable Power"] = "能量无常"
		L["Restless Strength"] = "充沛之力"
		L["Ephemeral Power"] = "短暂能量护符"
		L["Massive Destruction"] = "大规模杀伤性魔法"
		L["Arcane Potency"] = "奥术潜能"
		L["Energized Shield"] = "能量护盾"
		L["Brilliant Light"] = "辉煌之光"
		L["Mar'li's Brain Boost"] = "玛尔里的思想加速"
		L["Burst of Energy"] = "能量爆发"
		L["Refocus"] = "重新准备"
		L["Venomous Totem"] = "毒性图腾"
		L["Mind Quickening"] = "思维敏捷"
		L["Gift of Life"] = "生命赐福"
		L["Blinding Light"] = "盲目之光"
		L["Nature Aligned"] = "自然之盟"
		L["Earthstrike"] = "大地之击"
		L["Badge of the Swarmguard"] = "虫群卫士徽章"
		L["Speed"] = "速度"
		L["Immune Root/Snare/Stun"] = "免疫定身/缠绕/昏迷"
		L["Immune Fear/Polymorph/Snare"] = "免疫恐惧/变形/缠绕"
		L["Immune Charm/Fear/Stun"] = "免疫魅惑/恐惧/昏迷"
		L["Immune Charm/Fear/Polymorph"] = "免疫魅惑/恐惧/变形"
		L["Immune Fear/Polymorph/Stun"] = "免疫恐惧/变形/昏迷"
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = "冰霜反射器"
		L["Shadow Reflector"] = "暗影反射器"
		L["Fire Reflector"] = "火焰反射器"
		
		L["Healing Potion"] = "治疗药水"
		L["Healing Draught"] = "治疗药膏"
		L["Restore Mana"] = "恢复法力"
		L["Free Action"] = "自由行动"
		L["Living Free Action"] = "活力自由行动"
		L["Invulnerability"] = "无敌"
		L["Restoration"] = "恢复"
		L["Restore Energy"] = "恢复能量"

		L["Recently Bandaged"] = "新近包扎"
		L["Iron Grenade"] = "铁皮手雷"
		L["Thorium Grenade"] = "瑟银手雷"
		L["Goblin Sapper Charge"] = "地精工兵炸药"
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = "逃跑"
		L["Gnomish Rocket Boots"] = "侏儒火箭靴"
		L["Goblin Rocket Boots"] = "地精火箭靴"
		L["Running Speed"] = "跑步速度"
		L["Gnomish Mind Control Cap"] = "侏儒洗脑帽"
		L["Reckless Charge"] = "无畏冲锋"

		-- Warrior
		L["Charge"] = "冲锋"
		L["Mocking Blow"] = "惩戒痛击"
		L["Mortal Strike"] = "致死打击"
		L["Overpower"] = "压制"
		L["Retaliation"] = "反击风暴"
		L["Thunder Clap"] = "雷霆一击"
		L["Berserker Rage"] = "狂暴之怒"
		L["Bloodthirst"] = "嗜血"
		L["Challenging Shout"] = "挑战怒吼"
		L["Intercept"] = "拦截"
		L["Intimidating Shout"] = "破胆怒吼"
		L["Pummel"] = "拳击"
		L["Recklessness"] = "鲁莽"
		L["Whirlwind"] = "旋风斩"
		L["Bloodrage"] = "血性狂暴"
		L["Disarm"] = "缴械"
		L["Revenge"] = "复仇"
		L["Shield Bash"] = "盾击"
		L["Shield Block"] = "盾牌格挡"
		L["Shield Slam"] = "盾牌猛击"
		L["Shield Wall"] = "盾墙"

		-- Paladin
		L["Consecration"] = "奉献"
		L["Exorcism"] = "驱邪术"
		L["Hammer of Wrath"] = "愤怒之锤"
		L["Holy Wrath"] = "神圣愤怒"
		L["Lay on Hands"] = "圣疗术"
		L["Turn Undead"] = "超度亡灵"
		L["Blessing of Freedom"] = "自由祝福"
		L["Blessing of Protection"] = "保护祝福"
		L["Divine Intervention"] = "神圣干涉"
		L["Divine Protection"] = "圣佑术"
		L["Divine Shield"] = "圣盾术"
		L["Hammer of Justice"] = "制裁之锤"
		L["Judgement"] = "审判"
		L["Forbearance"] = "自律"

		-- Mage
		L["Blink"] = "闪现术"
		L["Portal: Darnassus"] = "传送门：达纳苏斯"
		L["Portal: Ironforge"] = "传送门：铁炉堡"
		L["Portal: Orgrimmar"] = "传送门：奥格瑞玛"
		L["Portal: Stormwind"] = "传送门：暴风城"
		L["Portal: Thunder Bluff"] = "传送门：雷霆崖"
		L["Portal: Undercity"] = "传送门：幽暗城"
		L["Blast Wave"] = "冲击波"
		L["Fire Blast"] = "火焰冲击"
		L["Fire Ward"] = "防护火焰结界"
		L["Cone of Cold"] = "冰锥术"
		L["Frost Nova"] = "冰霜新星"
		L["Frost Ward"] = "防护冰霜结界"
		L["Ice Barrier"] = "寒冰护体"
		L["Counterspell"] = "法术反制"
		L["Evocation"] = "唤醒"

		-- Rogues
		L["Kidney Shot"] = "肾击"
		L["Evasion"] = "闪避"
		L["Feint"] = "佯攻"
		L["Gouge"] = "凿击"
		L["Kick"] = "脚踢"
		L["Sprint"] = "疾跑"
		L["Blind"] = "致盲"
		L["Distract"] = "扰乱"
		L["Stealth"] = "潜行"
		L["Vanish"] = "消失"

		-- Shaman
		L["Reincarnation"] = "复生"
		L["Chain Lightning"] = "闪电链"
		L["Earth Shock"] = "地震术"
		L["Earthbind Totem"] = "地缚图腾"
		L["Fire Nova Totem"] = "火焰新星图腾"
		L["Flame Shock"] = "烈焰震击"
		L["Frost Shock"] = "冰霜震击"
		L["Stoneclaw Totem"] = "石爪图腾"
		L["Astral Recall"] = "星界传送"
		L["Grounding Totem"] = "根基图腾"
		L["Mana Tide Totem"] = "法力之潮图腾"

		-- Hunters
		L["Scare Beast"] = "恐吓野兽"
		L["Tranquilizing Shot"] = "宁神射击"
		L["Arcane Shot"] = "奥术射击"
		L["Concussive Shot"] = "震荡射击"
		L["Distracting Shot"] = "扰乱射击"
		L["Flare"] = "照明弹"
		L["Multi-Shot"] = "多重射击"
		L["Rapid Fire"] = "急速射击"
		L["Volley"] = "乱射"
		L["Counterattack"] = "反击"
		L["Disengage"] = "逃脱"
		L["Explosive Trap"] = "爆炸陷阱"
		L["Feign Death"] = "假死"
		L["Frost Trap"] = "冰霜陷阱"
		L["Immolation Trap"] = "献祭陷阱"
		L["Mongoose Bite"] = "猫鼬撕咬"
		L["Raptor Strike"] = "猛禽一击"
		L["Wyvern Sting"] = "翼龙钉刺"

		-- Warlocks
		L["Soulstone Resurrection"] = "灵魂石复活"
		L["Curse of Doom"] = "厄运诅咒"
		L["Death Coil"] = "死亡缠绕"
		L["Howl of Terror"] = "恐惧嚎叫"
		L["Inferno"] = "地狱火"
		L["Ritual of Doom"] = "末日仪式"
		L["Shadow Ward"] = "防护暗影结界"
		L["Conflagrate"] = "燃烧"
		L["Shadowburn"] = "暗影灼烧"
		L["Soul Fire"] = "灵魂之火"
		L["Devour Magic"] = "吞噬魔法"
		L["Spell Lock"] = "法术封锁"
		L["Lash of Pain"] = "剧痛鞭笞"
		L["Soothing Kiss"] = "安抚之吻"

		-- Priest
		L["Elune's Grace"] = "艾露恩的赐福"
		L["Feedback"] = "回馈"
		L["Power Word: Shield"] = "真言术：盾"
		L["Desperate Prayer"] = "绝望祷言"
		L["Fear Ward"] = "防护恐惧结界"
		L["Devouring Plague"] = "噬灵瘟疫"
		L["Fade"] = "渐隐术"
		L["Mind Blast"] = "心灵震爆"
		L["Psychic Scream"] = "心灵尖啸"
		
		-- Druid
		L["Barkskin"] = "树皮术"
		L["Faerie Fire"] = "精灵之火"
		L["Hurricane"] = "飓风"
		L["Nature's Grasp"] = "自然之握"
		L["Bash"] = "重击"
		L["Challenging Roar"] = "挑战咆哮"
		L["Cower"] = "畏缩"
		L["Dash"] = "急奔"
		L["Enrage"] = "狂怒"
		L["Frenzied Regeneration"] = "狂暴回复"
		L["Prowl"] = "潜伏"
		L["Tiger's Fury"] = "猛虎之怒"
		L["Rebirth"] = "复生"
		L["Tranquility"] = "宁静"
		
return end

if LOCALE == "zhTW" then
	-- Traditional Chinese translations go here
		--[[
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = ""
		L["Adrenaline Rush"] = ""
		L["Preparation"] = ""
		L["Ghostly Strike"] = ""
		L["Premeditation"] = ""
		L["Cold Blood"] = ""

		L["Bestial Wrath"] = ""
		L["Intimidation"] = ""
		L["Deterrence"] = ""
		L["Scatter Shot"] = ""
		L["Aimed Shot"] = ""

		L["Last Stand"] = ""
		L["Sweeping Strikes"] = ""
		L["Death Wish"] = ""
		L["Concussion Blow"] = ""

		L["Inner Focus"] = ""
		L["Power Infusion"] = ""
		L["Silence"] = ""

		L["Elemental Mastery"] = ""
		L["Stormstrike"] = ""
		L["Nature's Swiftness"] = ""

		L["Fel Domination"] = ""
		L["Amplify Curse"] = ""

		L["Divine Favor"] = ""
		L["Holy Shock"] = ""
		L["Holy Shield"] = ""
		L["Repentance"] = ""

		L["Innervate"] = ""
		L["Faerie Fire (Feral)"] = ""
		L["Feral Charge"] = ""
		L["Swiftmend"] = ""

		L["Presence of Mind"] = ""
		L["Arcane Power"] = ""
		L["Combustion"] = ""
		L["Cold Snap"] = ""
		L["Ice Block"] = ""

		-- Trinkets & Racials
		L["Will of the Forsaken"] = ""
		L["Perception"] = ""
		L["War Stomp"] = ""
		L["Stoneform"] = ""
		L["Cannibalize"] = ""
		L["Blood Fury"] = ""
		L["Berserking"] = ""
		L["Shadowmeld"] = ""
		L["Escape Artist"] = ""

		L["Brittle Armor"] = ""
		L["Unstable Power"] = ""
		L["Restless Strength"] = ""
		L["Ephemeral Power"] = ""
		L["Massive Destruction"] = ""
		L["Arcane Potency"] = ""
		L["Energized Shield"] = ""
		L["Brilliant Light"] = ""
		L["Mar'li's Brain Boost"] = ""
		L["Burst of Energy"] = ""
		L["Refocus"] = ""
		L["Venomous Totem"] = ""
		L["Mind Quickening"] = ""
		L["Gift of Life"] = ""
		L["Blinding Light"] = ""
		L["Nature Aligned"] = ""
		L["Earthstrike"] = ""
		L["Badge of the Swarmguard"] = ""
		L["Speed"] = ""
		L["Immune Root/Snare/Stun"] = ""
		L["Immune Fear/Polymorph/Snare"] = ""
		L["Immune Charm/Fear/Stun"] = ""
		L["Immune Charm/Fear/Polymorph"] = ""
		L["Immune Fear/Polymorph/Stun"] = ""
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = ""
		L["The Eye of the Dead"] = ""
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = ""
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = ""
		L["Shadow Reflector"] = ""
		L["Fire Reflector"] = ""
		
		L["Healing Potion"] = ""
		L["Healing Draught"] = ""
		L["Restore Mana"] = ""
		L["Free Action"] = ""
		L["Living Free Action"] = ""
		L["Invulnerability"] = ""
		L["Restoration"] = ""
		L["Restore Energy"] = ""

		L["Recently Bandaged"] = ""
		L["Iron Grenade"] = ""
		L["Thorium Grenade"] = ""
		L["Goblin Sapper Charge"] = ""
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = ""
		
		L["Sleep"] = ""
		L["Flee"] = ""
		L["Gnomish Rocket Boots"] = ""
		L["Goblin Rocket Boots"] = ""
		L["Running Speed"] = ""
		L["Gnomish Mind Control Cap"] = ""
		L["Reckless Charge"] = ""

		-- Warrior
		L["Charge"] = ""
		L["Mocking Blow"] = ""
		L["Mortal Strike"] = ""
		L["Overpower"] = ""
		L["Retaliation"] = ""
		L["Thunder Clap"] = ""
		L["Berserker Rage"] = ""
		L["Bloodthirst"] = ""
		L["Challenging Shout"] = ""
		L["Intercept"] = ""
		L["Intimidating Shout"] = ""
		L["Pummel"] = ""
		L["Recklessness"] = ""
		L["Whirlwind"] = ""
		L["Bloodrage"] = ""
		L["Disarm"] = ""
		L["Revenge"] = ""
		L["Shield Bash"] = ""
		L["Shield Block"] = ""
		L["Shield Slam"] = ""
		L["Shield Wall"] = ""

		-- Paladin
		L["Consecration"] = ""
		L["Exorcism"] = ""
		L["Hammer of Wrath"] = ""
		L["Holy Wrath"] = ""
		L["Lay on Hands"] = ""
		L["Turn Undead"] = ""
		L["Blessing of Freedom"] = ""
		L["Blessing of Protection"] = ""
		L["Divine Intervention"] = ""
		L["Divine Protection"] = ""
		L["Divine Shield"] = ""
		L["Hammer of Justice"] = ""
		L["Judgement"] = ""
		L["Forbearance"] = ""

		-- Mage
		L["Blink"] = ""
		L["Portal: Darnassus"] = ""
		L["Portal: Ironforge"] = ""
		L["Portal: Orgrimmar"] = ""
		L["Portal: Stormwind"] = ""
		L["Portal: Thunder Bluff"] = ""
		L["Portal: Undercity"] = ""
		L["Blast Wave"] = ""
		L["Fire Blast"] = ""
		L["Fire Ward"] = ""
		L["Cone of Cold"] = ""
		L["Frost Nova"] = ""
		L["Frost Ward"] = ""
		L["Ice Barrier"] = ""
		L["Counterspell"] = ""
		L["Evocation"] = ""

		-- Rogues
		L["Kidney Shot"] = ""
		L["Evasion"] = ""
		L["Feint"] = ""
		L["Gouge"] = ""
		L["Kick"] = ""
		L["Sprint"] = ""
		L["Blind"] = ""
		L["Distract"] = ""
		L["Stealth"] = ""
		L["Vanish"] = ""

		-- Shaman
		L["Reincarnation"] = ""
		L["Chain Lightning"] = ""
		L["Earth Shock"] = ""
		L["Earthbind Totem"] = ""
		L["Fire Nova Totem"] = ""
		L["Flame Shock"] = ""
		L["Frost Shock"] = ""
		L["Stoneclaw Totem"] = ""
		L["Astral Recall"] = ""
		L["Grounding Totem"] = ""
		L["Mana Tide Totem"] = ""

		-- Hunters
		L["Scare Beast"] = ""
		L["Tranquilizing Shot"] = ""
		L["Arcane Shot"] = ""
		L["Concussive Shot"] = ""
		L["Distracting Shot"] = ""
		L["Flare"] = ""
		L["Multi-Shot"] = ""
		L["Rapid Fire"] = ""
		L["Volley"] = ""
		L["Counterattack"] = ""
		L["Disengage"] = ""
		L["Explosive Trap"] = ""
		L["Feign Death"] = ""
		L["Frost Trap"] = ""
		L["Immolation Trap"] = ""
		L["Mongoose Bite"] = ""
		L["Raptor Strike"] = ""
		L["Wyvern Sting"] = ""

		-- Warlocks
		L["Soulstone Resurrection"] = ""
		L["Curse of Doom"] = ""
		L["Death Coil"] = ""
		L["Howl of Terror"] = ""
		L["Inferno"] = ""
		L["Ritual of Doom"] = ""
		L["Shadow Ward"] = ""
		L["Conflagrate"] = ""
		L["Shadowburn"] = ""
		L["Soul Fire"] = ""
		L["Devour Magic"] = ""
		L["Spell Lock"] = ""
		L["Lash of Pain"] = ""
		L["Soothing Kiss"] = ""

		-- Priest
		L["Elune's Grace"] = ""
		L["Feedback"] = ""
		L["Power Word: Shield"] = ""
		L["Desperate Prayer"] = ""
		L["Fear Ward"] = ""
		L["Devouring Plague"] = ""
		L["Fade"] = ""
		L["Mind Blast"] = ""
		L["Psychic Scream"] = ""
		
		-- Druid
		L["Barkskin"] = ""
		L["Faerie Fire"] = ""
		L["Hurricane"] = ""
		L["Nature's Grasp"] = ""
		L["Bash"] = ""
		L["Challenging Roar"] = ""
		L["Cower"] = ""
		L["Dash"] = ""
		L["Enrage"] = ""
		L["Frenzied Regeneration"] = ""
		L["Prowl"] = ""
		L["Tiger's Fury"] = ""
		L["Rebirth"] = ""
		L["Tranquility"] = ""
		]]--
		
return end